version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: tyrant
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookmark
    networks:
      - freecodecamp
networks:
  freecodecamp:
